### ISSUE TITLE
Maintainer Wanted!

### ISSUE THREAD

**Issue by herrstucki** [dazuaz/responsive-loader#104]
Since I don't have the focus and time to maintain this repo anymore, I'm looking for someone to hand over the ownership of it and the npm package.

I think the best would be to move this to a separate org/user or ideally [webpack-contrib](https://github.com/webpack-contrib) (I'm not sure what's required to do that). Probably someone who already maintains an active fork of this would be best suited to take this over.

Thanks for all your contributions and patience, and I hope this small piece of software will have a bright future in someone else's hand 💖

**Comment by antonk52** [comment]
Hello. Thank you for all the time and effort you've put into this project. I've used it in multiple projects in the past and found it really useful. I would be happy to take of it in the future and work to get the handing PRs and to close the awaited issues. Please let me know if I can be at any help for this project =)

**Comment by dscafati** [comment]
I'm sorry to read that it was not accepted on webpack-contrib. I'll be happy to help with the project in any way

**Comment by strarsis** [comment]
@herrstucki, @antonk52: Yes, please! This loader is immensely useful! I use it for resizing lots of images in frontend for offering adaptive resolutions using CSS media queries, `<img>` `srcset`/`sizes` and `<picture>`. Now I also need support for `webp` format and additional parameters and bug fixes.

**Comment by strarsis** [comment]
@herrstucki, @antonk52, @dscafati: I mean, is nobody else using webpack and images and needs to resize them? FLIF is not supported by the browsers yet... Had webpack already been replaced by something else? I simply can't wrap my mind around that there is no demand for such a loader...

**Comment by dscafati** [comment]
@herrstucki after seeing how much time it has passed without any news I would like to propose myself (now formally) to mantain the project. I don't have that much availability but I think I can give the repo a review at least once every week. It's a shame this repo doesn't get updated being it so useful

**Comment by dazuaz** [comment]
@herrstucki Hey, I would be happy to maintain the project, I have already made some progress on this repo https://github.com/dazuaz/responsive-images-loader.

**Comment by herrstucki** [comment]
@dazuaz and @dscafati: thanks for stepping up (and sorry again for not responding for a long time)!

Probably the easiest way would be to transfer the repo to you @dazuaz (since you already started working on the code), then you can keep the issues and PRs of this repo instead of having to start over … unless you want that 😄 In that case I could also just put up a notice in the README pointing to your repo.

For the npm package we also could go both ways: either transfer ownership OR deprecate the latest version and point to your package.

Any opinions on how this should be handled?

**Comment by dazuaz** [comment]
@herrstucki: Thanks for creating it!
I think transferring both might better to maintain continuity with the community, and it will be a less confusing transition.

**Comment by strarsis** [comment]
Yes, please! I just want to npm install and use it.

**Comment by dazuaz** [comment]
@herrstucki Hey, not sure if you got my message, but I am happy with whatever you think is the best option.

Maybe transferring only the npm package and then release a 2.0.0 alpha to a new repo ```dazuaz/responsive-loader```, and we put the notice on this repo.

Let me know what you think

**Comment by herrstucki** [comment]
@dazuaz Transfer request for the repo sent! I agree it's better to keep the whole issues history etc. I also added you as a maintainer to the npm package 🤗
