### ISSUE TITLE
Can't use it with typescript because module not found

### ISSUE THREAD

**Issue by stevemarksd** [dazuaz/responsive-loader#105]
I'm getting this error when I check types

![image](https://user-images.githubusercontent.com/58653359/77312087-44ebf080-6d3c-11ea-818a-15bb79343e43.png)

To reproduce:

```
import afrom '../a.png?sizes[]=111'
```

I wonder how all other people are using this library without running into this issue?

**Comment by mormahr** [comment]
You can always ignore warnings with a `//@ts-ignore` comment before the import.

Otherwise you can [create a type definition](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html). It would indeed be nice if there was a definition available, but so far i haven't found one and i'm too lazy to create one myself, so i use it as `any`.

**Comment by Porges** [comment]
I use a definition like this (in `react-app-env.d.ts` as I am using `create-react-app`):

```js

type ResponsiveImageOutput = 
    { src: string
    , srcSet: string
    , placeholder: string
    , images: {path: string, width: number, height: number}[]
    , width: number
    , height: number
    }

declare module '*.jpg' {
    const content: ResponsiveImageOutput
    export default content;
}

declare module '*.jpeg' {
    const content: ResponsiveImageOutput
    export default content;
}

declare module '*.png' {
    const content: ResponsiveImageOutput
    export default content;
}

```

**Comment by ajantsch** [comment]
@Porges I tried adding these definitions to my `custom.d.ts` but the `import` statement still gives me the `Module cannot be found` error. Is there anything else necessary to make this work? FYI I'm using webpack, not CRA.

**Comment by evoactivity** [comment]
For each set of query params I use I add another module definition to my global.d.ts eg

```typescript
declare module '*.png' {
  const content: any;
  export default content;
}

declare module '*.png?placeholder=true&sizes[]=300,sizes[]=600,sizes[]=1024,sizes[]=2048' {
  const content: any;
  export default content;
}
```

Ideally we could use multiple wildcards and just use

```typescript
declare module '*.png' {
  const content: any;
  export default content;
}
```

but that would require this issue to be addressed by typescript https://github.com/microsoft/TypeScript/issues/38638
