### ISSUE TITLE
Future of this repostiory ?

### ISSUE THREAD

**Issue by TessyPowder** [dazuaz/responsive-loader#111]
Theres a [new fork](https://github.com/dazuaz/responsive-images-loader) of this repository, that improves many things (like resized webp picures).
As far as i know it was created, because development in this repository was to slow.
@herrstucki Will you continue development here or should all new development moved to @dazuaz [new repository](https://github.com/dazuaz/responsive-images-loader) ?
If theres no new development here PLEASE mark this as archived, because people will create Pull Requests and the two repositories will grow apart.
It's currently already confusing enough to read the Pull Requests to find out how i get resized webp images and create the alias, so that libaries based on this repository still work.
The version of @dazuaz works perfectly btw.

**Comment by herrstucki** [comment]
@TessyPowder per #104 I transferred ownership to @dazuaz, who will take care of this project from now on.
