### ISSUE TITLE
2.0.1 Build error: cannot find module ... node_modules/responsive-loader/lib/cjs.js/sharp

### ISSUE THREAD

**Issue by abbott** [dazuaz/responsive-loader#113]
> Build error occurred
> Error: Cannot find module '[localPath]/node_modules/responsive-loader/lib/cjs.js/sharp'

when I replace cjs with index in the package the error goes away...
`"main": "lib/cjs.js"` >>> `"main": "lib/index.js"`

I confirmed on my other machine that switching from v2.0.0 to 2.0.1 results in the same error, and switching back to 2.0.0 restores the build successfully.

### Dependencies...

- responsive-loader ^2.0.1
- sharp ^0.25.4
- next-optimized-images ^2.6.2
- next ^9.5.2
- vercel CLI 20.0.0-canary.18

**Comment by dazuaz** [comment]
@abbott thanks for reporting this,

next-optimized-images is [inferring the sharp adapter](https://github.com/cyrilwanner/next-optimized-images/blob/fe31e5c77008a88ce9ffe76d504229562ad8a549/lib/loaders/responsive-loader.js#L17)

One quick fix is to specify it in the config of next-optimized-images
```
...
    optimizedImages,
    {
      responsive: {
        adapter: require("responsive-loader/sharp"),
      },
...
```

**Comment by abbott** [comment]
No problem. Turns out my config had that rule implemented incorrectly which 2.0.1 helped surface. 

### ✔ Confirming suggested fix resolves build issue in **2.0.1** and later.

Closing 👍

**Comment by meoyawn** [comment]
hey @abbott , what was the error in your config? Trying to solve this same issue

**Comment by abbott** [comment]
> hey @abbott , what was the error in your config? Trying to solve this same issue

it was just a typo, but it did not error in the build. If it helps, here are the image rules in my config...
```
const withPlugins = require('next-compose-plugins');
const withOptimizedImages = require('next-optimized-images');

const optimizedImages = [
  withOptimizedImages, {
    test: /\.(jpe?g|png|webp)$/i,
    loader: 'responsive-loader',
    optimizeImagesInDev: false,
    handleImages: ['jpeg', 'png', 'svg', 'webp', 'gif', 'ico'],
    responsive: {
      adapter: require('responsive-loader/sharp'),
    },
  },
]

const plugins = [optimizedImages];
module.exports = withPlugins(plugins, nextConfig);
```

**I omitted my nextConfig object.**
