### ISSUE TITLE
Jest dependency?

### ISSUE THREAD

**Issue by Munter** [dazuaz/responsive-loader#120]
Why is Jest marked as an optional dependency?

It causes quite the explosion of dependencies when I add responsive-loader as a dependency on my project.

It seems that Jest should be moved to `devDependencies`

**Comment by dazuaz** [comment]
Error on my part, thanks for reporting!

**Comment by kopax** [comment]
Did you manage to use this plugin with Jest? It keeps failing when using `?format=webp` imports:

    Cannot find module '../../../assets/images/business/skyscraper-1149478_1920-xl.jpg?format=webp' from 'src/components/sections/careers/Careers.js'
