### ISSUE TITLE
Ominous "cannot destructure property height" issue (with reproducable demo)

### ISSUE THREAD

**Issue by FunctionDJ** [dazuaz/responsive-loader#135]
The error:
![image](https://user-images.githubusercontent.com/34871211/104121791-550fa380-5341-11eb-950b-e3002da1a4f2.png)

I've encountered the issue above and was able to replicate it in a minimalistic project you can checkout here: https://github.com/FunctionDJ/rl-test

I'm not sure who's the culprit here: `responsive-loader`, `sharp`, `webpack` or myself.

**Comment by dazuaz** [comment]
@FunctionDJ Hello,

This is due to a corrupt png

```bash
$ pngcheck test/icon.png                                                                                                                                                                                      
test/icon.png  CRC error in chunk iCCP (computed a2ee8208, expected 59869ddc)
```
