### ISSUE TITLE
Error: Cannot find module './image.jpg?resize&size=534'

### ISSUE THREAD

**Issue by Kalle-Elmdahl** [dazuaz/responsive-loader#141]
I have this code to import images
```javascript
const gallery = array.map(({image, size}) => {            
    const jpg = require('../../../public/images/' + image + '?resize&size=' + size)
    const webp = require('../../../public/images/' + image + '?resize&size=' + size + '&format=webp')
    
    return {
        webp,
        jpg
    }
})
```

This code does not work, and i get this error:

Error: Cannot find module './image.jpg?resize&size=534'

But when i change the size variable to a constant like this:
```javascript
const gallery = array.map(({image, size}) => {            
    const jpg = require('../../../public/images/' + image + '?resize&size=' + 534)
    const webp = require('../../../public/images/' + image + '?resize&size=' + 534 + '&format=webp')
    
    return {
        webp,
        jpg
    }
})
```
It works fine.

This is a next js project and here is my package.json:
```  
"dependencies": {
    "date-fns": "^2.22.1",
    "image-size": "^1.0.0",
    "imagemin-mozjpeg": "^8.0.0",
    "imagemin-optipng": "^8.0.0",
    "mongodb": "^3.6.9",
    "next": "^10.2.3",
    "next-optimized-images": "^2.6.2",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "responsive-loader": "^2.0.0",
    "sass": "^1.34.1",
    "sharp": "^0.28.3",
    "swiper": "^6.7.0",
    "webp-loader": "^0.6.0"
  }
 ```

I am thankful for any help!

**Comment by dazuaz** [comment]
@Kalle-Elmdahl Hello,

Not sure why, you could try using version 3 ```npm install responsive-loader@next```

**Comment by Kalle-Elmdahl** [comment]
Tried it and it did not help. I have tried many different ways of doing this but it seems like the options part of the path can't use variables at all. Could this be the case?

For example this works:
```javascript
require(`${imagepath}?resize&size=500`)
```

But this does not:
```javascript
const size = 1000
require(`./public/images/image.jpg?resize&size=${size}`)
```

**Comment by Trinovantes** [comment]
That's intentional by webpack's design

When it sees an import with a dynamic file name, it has to bundle every possible file it could match. When it sees a dynamic query, it can't bundle every possible query value so it won't process the import.

Even if the query is a statically known value, AFAIK the webpack compiler doesn't perform static variable replacement.
