### ISSUE TITLE
Images double-bundled and wrong name in css file

### ISSUE THREAD

**Issue by cybergrunge** [dazuaz/responsive-loader#146]
Hi, 
I'm using sass-loader, postcss-loader, css-loader and mini-css-extract-plugin.

When I add responsive-loader, images are bundled two times, and their hashed name in the CSS file is not the one generated by responsive-loader.

I tried to set 'url: false' in css-loader options, but then no image is being bundled, even by responsive-loader.

Any idea?

**Comment by dazuaz** [comment]
Inactive, please reopen if problem persists
