### ISSUE TITLE
responsive-loader does not work on react-scripts 5.0.0

### ISSUE THREAD

**Issue by quocvan1311** [dazuaz/responsive-loader#148]
I faced the issue that the image file got loaded when using react-scripts 5.0.0 is a base64 string (but the content is not the image also).
For react-scripts 4.0.3, it works normally as it returned the object { src, srcSet... }.
Here is my rules for the loader
```
      {
        test: /\.(jpe?g|png|webp)$/i,
        type: "javascript/auto",
        use: [
          {
            loader: "responsive-loader",
            options: {
              adapter: require("responsive-loader/sharp")
            }
          }
        ]
      }
```

**Comment by dazuaz** [comment]
Solved in version 3 that supports webpack 5
