### ISSUE TITLE
[BUG] Using `html-loader` and responsive image with JSON notation occurs ERROR

### ISSUE THREAD

**Issue by webdiscus** [dazuaz/responsive-loader#154]
The problem appear when used `html-loader` and responsive image with JSON notation, like this
```
<img src="/path/to/image.jpg?{size:200, format: 'webp'}">
```
 then `html-loader` transform URL form `src` into `require('/path/to/image.jpg?{size:200, format: 'webp'}')`,
 that occurs ERROR by `html-loader` because the `format: 'webp'` contains single quotes and `require('...')` too.

When I use  the accent char '`' to wrap a string param:
```
<img src="/path/to/image.jpg?{size:200, format: `webp`}">
```
then occurs SyntaxError
```
JSON5: invalid character '`'
```

### The solution: 
Encode JSON query and fix single quotes `'` with `%27`:

```
let data = encodeURIComponent('{size:105, format: %27webp%27, placeholder: true}');
```

then the encoded query look like:
```
<img src="/path/to/image.jpg?{size%3A105%2C format%3A %27webp%27%2C placeholder%3A true}">
```
Now this query can be decoded, but in `lib/parseQuery.js` in the function `parseQuery()` an JSON query is not decoded:

```js
   if (query.substr(0, 1) === '{' && query.substr(-1) === '}') {
        return JSON5.parse(query);
    }
```

My proposition:
```js
   if (query.substr(0, 1) === '{' && query.substr(-1) === '}') {
++      query = decodeURIComponent(query); // <-- please add this code line
        return JSON5.parse(query);
    }
```
then it works fine.

P.S.  of cause I can use standard query syntax:
```
<img src="/path/to/image.jpg?size=200&format=webp">
```
and it would be better to support all use cases :-)

Thank You for this amazing module!

**Comment by dazuaz** [comment]
Alternatively, can you try to use the following notation (swap single quotes and double quotes):

```<img src='/path/to/image.jpg?{size:200, format: "webp"}'>```

Let me know if that will let it play nice with ```html-loader```

**Comment by webdiscus** [comment]
> Alternatively, can you try to use the following notation (swap single quotes and double quotes):
> 
> `<img src='/path/to/image.jpg?{size:200, format: "webp"}'>`
> 
> Let me know if that will let it play nice with `html-loader`

In the `html-loader` cannot  be used single or double quotes in query, because following:
```
<img src='/path/to/image.jpg?{size:200, format: "webp"}'>
```

inner of `html-loader` will be transformed to:
```
<img src="/path/to/image.jpg?{size:200, format: "webp"}">
```

here is again Parse Error: `src="...{"webp"}"`

The reserved query characters must be encoded and in your `parseQuery() function` decoded.
In the `parseQuery() function` overall is already used the `decodeURIComponent`, expect one place in code - `JSON5.parse(query);`


```js
function parseQuery(query) {
    if (query.substr(0, 1) !== '?') {
        throw new Error("A valid query string passed to parseQuery should begin with '?'");
    }
    query = query.substr(1);
    if (!query) {
        return {};
    }
    if (query.substr(0, 1) === '{' && query.substr(-1) === '}') {
        return JSON5.parse(query); // <---- HERE should be added the decodeURIComponent(query)
    }
    const queryArgs = query.split(/[,&]/g);
    const result = {};
    queryArgs.forEach((arg) => {
        const idx = arg.indexOf('=');
        if (idx >= 0) {
            let name = arg.substr(0, idx);
            let value = decodeURIComponent(arg.substr(idx + 1));
            // const specialValues: LooseObject = {}
            // eslint-disable-next-line no-prototype-builtins
            if (specialValues.hasOwnProperty(value)) {
                value = specialValues[value];
            }
            if (name.substr(-2) === '[]') {
                name = decodeURIComponent(name.substr(0, name.length - 2));
                if (!Array.isArray(result[name])) {
                    result[name] = [];
                }
                result[name].push(value);
            }
            else {
                name = decodeURIComponent(name);
                result[name] = value;
            }
        }
        else {
            if (arg.substr(0, 1) === '-') {
                result[decodeURIComponent(arg.substr(1))] = false;
            }
            else if (arg.substr(0, 1) === '+') {
                result[decodeURIComponent(arg.substr(1))] = true;
            }
            else {
                result[decodeURIComponent(arg)] = true;
            }
        }
    });
    return result;
}
```

**Comment by dazuaz** [comment]
3.0.4 has the suggested fix implemented, hope that solves the issue.

**Comment by webdiscus** [comment]
@dazuaz 

Thank you very much!
Now it's work. The problem is solved.
