### ISSUE TITLE
Windows - generation of hash image files in dist folder

### ISSUE THREAD

**Issue by silveoj** [dazuaz/responsive-loader#157]
### System
I use Windows 10. NodeJS `14.17.0`,`16.9.1` or any version. Python3 (`3.*`) is installed with PATH environment.
With Linux/Mac is ok.

### Description
`dist/assets/img` includes correctly converted images (webp, jpg) but

- HTML/CSS link to hash image names `background-image: url(ccda94791a5285436ba2.png?size=200&format=webp);`
- `dist` folder contains hash `png` files (1 Kb each, can't open) (parallel with dist JS, CSS, HTML): `dist/13aebb007756697c0f96.png`

### Example
Repo: https://github.com/silveoj/pug-plugin-responsive-loader-issue/tree/responsive-loader-windows-test
Branch: `responsive-loader-windows-test`
See `result.png`.

I have worked with https://github.com/webdiscus/pug-plugin
I supposed issue with this plugin https://github.com/webdiscus/pug-plugin/issues/8
But I have removed `pug-plugin` and have used only `responsive-loader`. Issue is still here (see this branch).

**Comment by webdiscus** [comment]
I found the problem in pug-plugin with a path under windows. I will fix it.
This issue here can be closed.
