### ISSUE TITLE
Resize and serve remote images?

### ISSUE THREAD

**Issue by itsmejoeeey** [dazuaz/responsive-loader#161]
Hi there,

I cannot find any mention in the documentation about support for optimizing remote images (like [is possible with the built-in Next.js image optimization solution](https://nextjs.org/docs/basic-features/image-optimization#remote-images)).

If this use-case isn't supported, are there plans in the roadmap? Any workaround ideas?

**Comment by dazuaz** [comment]
@itsmejoeeey this package is a loader for webpack, witch it is a bundler. So depending on your needs it can help you if there is a build step involve, you could fetch the remote image and include the new images with your new image, but if you need support for generating responsive images on the fly, this package will not be what you need.
