### ISSUE TITLE
Custom contenthash length in options.name

### ISSUE THREAD

**Issue by kde3kko** [dazuaz/responsive-loader#162]
Is there a way to specify a custom contenthash length?
It seems the loader is ignoring the custom length placeholder option for contenthash, e.g. 
```js
options: {
    ...
    name: '[path][name]-[width].[contenthash:8].[ext]',
    ...
}
```

Because of server config not directly under my control I need the contenthash to be exactly 8 char long, but when using this config, the `8`is ignored, and the file is written to disk with a 32 char long contenthash.

I managed to overcome this by manually truncating the produced filename inside the ```outputPath``` config function but this obviuously feels hackish.

It looks like this is [totally intentional](https://github.com/dazuaz/responsive-loader/blob/711a604fa9eeb3afe74f2300b0bb4ea693c43c0d/src/interpolateName.ts#L75) on your side, so I'd like to know:

1) Why is this by design?
2) Is there a better way to overcome my (silly, I know) problem?

Kudos for your great work,
and thank you for taking the time to read this (probably trivial) issue!

**Comment by dazuaz** [comment]
@kde3kko Thanks for reporting this out, just published a new version that corrects this issue, please update and let me know how it goes. 

To give you more context, the interpolateName utility was discontinued when webpack 5 came out, but looking back at it, it has been updated and supported, so I have change the package to use that again, and now it correctly parses the name.
