### ISSUE TITLE
After upgrading to 3.1.0 absolute url scheme is corrupted (https:// rewritten to https:/)

### ISSUE THREAD

**Issue by rawpixel-vincent** [dazuaz/responsive-loader#163]
In 3.0.4, output for src and srcset:

```
https://custom.domain.com/_next/static/images/image-hash.jpg
```

in 3.1.0, `https://` is rewritten to `https:/`

```
https:/custom.domain.com/_next/static/images/image-hash.jpg
```

**Comment by dazuaz** [comment]
@rawpixel-vincent can you please update to 3.1.1 and check if the issue is fixed for you? If not, could you please share your config.
