### ISSUE TITLE
Fix `pass` option to skip image resizing

### ISSUE THREAD

**Issue by alex-ketch** [dazuaz/responsive-loader#30]
It is not always necessary to output resized images, local development for instance, and this becomes cumbersome if you need to stop and start the local build process.

I'd like to clean up the `pass` option to simply spit out the original image, without resizing it.

Currently this partially works but I'm getting corrupted images, and no placeholder data URI output.
Height & Width would be that of the original image.

For placeholder I see three approaches:
1. Encode the image at original size
  - Will potentially lead to very long URIs
  - Will need to do speed tests
2. Scale down and output at the placeholder size setting
  - Slow, as we'll have to resize the image. Could be mitigated by #29 
3. Hard code a small image when using this option

A side question, is a more explicit option name better? `skip` for example?

What do you think @herrstucki?

**Comment by noth8** [comment]
You can use webpack.dev.config.js for this : 
**webpack.config.js** : 
```
module.exports = (env, options) => {
    if (options.mode === "production")
        return conf;
    else
        return require(path.resolve(__dirname, "webpack.dev.config.js"));
}
```
**package.json**:
```
  "scripts": {
    "dev": "webpack-dev-server --mode development",
    "bdev": "webpack --mode development",
    "prod": "webpack --mode production"
  },
```

**Comment by dazuaz** [comment]
Can use ```disable``` option
