### ISSUE TITLE
Add option to output no files at all

### ISSUE THREAD

**Issue by qm3ster** [dazuaz/responsive-loader#33]
A valuable option would be to only make the URL-encoded placeholder version, plus srcSet and src for requested sizes clamped to real file size. The custom name formatting + publicPath will then allow requesting the resized images from imgIX or Cloudinary, which handle things static hosting can't easily do such as accept headers for webp.

**Comment by herrstucki** [comment]
How about the ability of _just_ importing a placeholder (currently not possible but quite simple to add)? I think it's a bit pointless to specify sizes as loader options and also adding a custom output format in order to create CDN-friendly URLs.

For example:

```js
// Just import the placeholder
const responsiveImage = require('responsive?placeholder=true!myImage.jpg');

// Not part of loader's responsibility
const srcSet = getCDNSrcset('myImage.jpg');

return <img src={responsiveImage.placeholder} srcSet={srcSet} />
```

But maybe you have something else in mind?

**Comment by qm3ster** [comment]
I meant that since you are already doing `const name = query.name || options.name || '[hash]-[width].'` the formatter functionality is essentially there.
You already output an array of urls with different widths after checking for max size.
With the options set in the webpack config, it's possible to get (with a single require statement):
1. an encoded placeholder
1. checking for maximum size out of the list to avoid upscaling requests
1. a list of urls including the width token

It's basically usable as it is now, besides the fact that I would have to delete the emitted files before deploying. (plus the time jimp spent making them)
