### ISSUE TITLE
Cache/reuse output files if newer than the source files

### ISSUE THREAD

**Issue by qbolec** [dazuaz/responsive-loader#41]
It seems that the rescaling of assets is currently one of the longest (~1m) parts of our build right now, and I wonder if this step is even needed at all, since the static files do not change.

Some details:
* There are input images: 
** 8 jpegs with total size 2 289 723 bytes
** 4 pngs with total size 2 009 442 bytes
* There are 40 output images with total size 5 163 055 bytes

**Comment by herrstucki** [comment]
Hard to tell where your problem is without more information (how many images * sizes, which version, which adapter etc.) …

Anyway, you may want to look into using https://github.com/webpack-contrib/cache-loader in conjunction with this loader. I haven't tested it but would be interested if it solves your issue.

**Comment by qbolec** [comment]
I use
```
 "responsive-loader": "1.1.0",
```
and import images like this:
```
import heroImage from '../../../resources/images/faq.jpg?{"sizes": [1920, 768, 1180, 3840]}'
```
and webpack.config.js is like this:
```
      {
        test: /\.(jpe?g|png)$/i,
        loader: 'responsive-loader',
        options: {
          format: 'jpg',
        },
      },
```

**Comment by qbolec** [comment]
Thank you for your advice!
Changing the config to:
```
{
        test: /\.(jpe?g|png)$/i,
        use: [
           'cache-loader',
          {
            loader: 'responsive-loader',
            options: {
              format: 'jpg',
            },
          }
        ],
      },
```
made the `time yarn build` drop to 20 seconds, from the previous 1 minute!
If I `touch` one of the input files, then it correctly resizes only that single image, and the time is around 24 seconds.

Thank you!

**Comment by qbolec** [comment]
I'm just curious if this indeed caches the resulting images, or just the json with description of them?
For example, if I look into one of the `.cache-loader/<hash>.json` files, I see this:
```
{
  "remainingRequest": "/Users/kuba/Documents/op/capacity-for-work-web/node_modules/responsive-loader/lib/index.js??ref--3-1!/Users/kuba/Documents/op/capacity-for-work-web/src/main/resources/images/service-implementation.jpg?{\"sizes\": [1920, 768, 1180, 3840]}",
  "dependencies": [
    {
      "path": "/Users/kuba/Documents/op/capacity-for-work-web/src/main/resources/images/service-implementation.jpg",
      "mtime": 1507032008000
    },
    {
      "path": "/Users/kuba/Documents/op/capacity-for-work-web/node_modules/cache-loader/dist/cjs.js",
      "mtime": 1493198456000
    },
    {
      "path": "/Users/kuba/Documents/op/capacity-for-work-web/node_modules/responsive-loader/lib/index.js",
      "mtime": 1499851130000
    }
  ],
  "contextDependencies": [],
  "result": [
    "module.exports = {srcSet:__webpack_public_path__ + \"358474937a6e7810d8b76ca26bbd68e0-1200.jpg 1200w\"+\",\"+__webpack_public_path__ + \"514e1cbcda06bd24a50ad1c3c6850df6-768.jpg 768w\"+\",\"+__webpack_public_path__ + \"732668f9c1b8bc72f31ac277c80bce07-1180.jpg 1180w\",images:[{path:__webpack_public_path__ + \"358474937a6e7810d8b76ca26bbd68e0-1200.jpg\",width:1200,height:800},{path:__webpack_public_path__ + \"514e1cbcda06bd24a50ad1c3c6850df6-768.jpg\",width:768,height:512},{path:__webpack_public_path__ + \"732668f9c1b8bc72f31ac277c80bce07-1180.jpg\",width:1180,height:787}],src:__webpack_public_path__ + \"358474937a6e7810d8b76ca26bbd68e0-1200.jpg\",toString:function(){return __webpack_public_path__ + \"358474937a6e7810d8b76ca26bbd68e0-1200.jpg\"},placeholder: undefined,width:1200,height:800};"
  ]
}
```
which looks like, there is no real "pixel colors data" in here, and I'm affraid that the `responsive-loader` creates these images as a side effect of generating this `module.exports`, and this side effect is not cached. 
That would be probably fine, if the paths to resulting images were listed in the `dependencies` section, but it is not, so I am worried.

**Comment by herrstucki** [comment]
I'm not really familiar with how cache-loader actually works but I assume it compares the input to the following loader (listed in `dependencies`) with previous runs and only runs that loader if any of them has changed. So if cache-loader skips the following loader completely, no new files should be emitted.

Again, I'm not aware of the rest of your webpack setup but I assume that when you run `yarn build`, you also minify your javascript code which would be responsible for the majority of your 20–24s build.

**Comment by dazuaz** [comment]
There is an experimental cache option now available, open a new discussion to go over that specifically .
