### ISSUE TITLE
webp export

### ISSUE THREAD

**Issue by dlebedynskyi** [dazuaz/responsive-loader#42]
Any change to add webp as an option? 
Ideally it would be nice to build something like 
```
<picture>
    <!--[if IE 9]><video style="display: none;"><![endif]-->
    <source type="image/webp" srcset="2700x1209/rocket-pods-mr-ben-01-2700x1209.webp 2700w, 
                    1800x806/rocket-pods-mr-ben-01-1800x806.webp 1800w, 
                    1536x1536/rocket-pods-mr-ben-01-1536x1536.webp 1536w, 
                    1024x1024/rocket-pods-mr-ben-01-1024x1024.webp 1024w, 
                    900x900/rocket-pods-mr-ben-01-900x900.webp 900w, 
                    600x600/rocket-pods-mr-ben-01-600x600.webp 600w" 
            sizes="100vw" />
    <source srcset="2700x1209/rocket-pods-mr-ben-01-2700x1209.jpg 2700w, 
                    1800x806/rocket-pods-mr-ben-01-1800x806.jpg 1800w, 
                    1536x1536/rocket-pods-mr-ben-01-1536x1536.jpg 1536w, 
                    1024x1024/rocket-pods-mr-ben-01-1024x1024.jpg 1024w, 
                    900x900/rocket-pods-mr-ben-01-900x900.jpg 900w, 
                    600x600/rocket-pods-mr-ben-01-600x600.jpg 600w" 
            sizes="100vw" />
    <!--[if IE 9]></video><![endif]-->
    <img class="rsImg" src="600x600/rocket-pods-mr-ben-01-600x600.jpg" alt="Visit MrBen" />
</picture>
```

**Comment by herrstucki** [comment]
Good idea! I'd be happy to accept a PR adding this feature 👍 

The only concern I have would be that [jimp doesn't support webp yet](https://github.com/oliver-moran/jimp/issues/144), so we'd need to handle that accordingly.

**Comment by blowsie** [comment]
Hi @herrstucki , since Sharp supports webp, what work would need to be done get get responsive-loader to support wepb with sharp? How can I help / develop this feature?

**Comment by JannikZed** [comment]
Hi there, we would really need to use the responsive loader with webp images, as they are the new web-image standard! This issue is open since 2017 - is there any chance we can realize this functionality fast and easy? What is currently blocking?

**Comment by strarsis** [comment]
@herrstucki: Is there an "official" fork of this repository so I can also have webp support?

**Comment by dazuaz** [comment]
webp support added!

**Comment by kopax** [comment]
Hi and thanks for adding the feature, is there a  way to enable `?format=webp` by default for all imports ?
