### ISSUE TITLE
Cache loader?

### ISSUE THREAD

**Issue by strarsis** [dazuaz/responsive-loader#52]
Does it make sense using the webpack [cache-loader](https://github.com/webpack-contrib/cache-loader) with this responsive-loader for speeding up builds?

**Comment by herrstucki** [comment]
I haven't tried but I think it makes sense.

**Comment by daniel100097** [comment]
`{
    test: /\.(jpe?g|png)$/i,
    use: [{
        loader: "cache-loader",
    }, {
        loader: "url-loader",
        options: {
            adapter: require("responsive-loader/jimp"),
            fallback: "responsive-loader",
            limit: 8192,
            sizes: isProd() ? [720, 1024, 1920] : [1920],
            format: "png",
        },
    }],

}`

**Comment by strarsis** [comment]
@daniel100097: Thanks, but when I try the code no resized image files are mitted anymore.
`sharp` is used instead of `jimp` in this setup, maybe this causes the issue?

**Comment by strarsis** [comment]
@DotIN13: Awesome! Thanks.

**Comment by slorber** [comment]
@DotIN13  are the resized images cached in the `node_modules/.cache/webpack` folder too as a .pack file?

**Comment by DotIN13** [comment]
> @DotIN13 are the resized images cached in the `node_modules/.cache/webpack` folder too as a .pack file?

As I see it, the cache config I posted does not involve a `node_modules/.cache` directory

**Comment by slorber** [comment]
@DotIN13 it's the default cache location.

Do to reword my question: do you see images in .webpack-cache? Or do you fthink images are in a pack file?

**Comment by DotIN13** [comment]
> @DotIN13 it's the default cache location.
> 
> Do to reword my question: do you see images in .webpack-cache? Or do you fthink images are in a pack file?

Okay, yes, image caches were bundled in `.pack` files by webpack.
