### ISSUE TITLE
Possible to add png optimization?

### ISSUE THREAD

**Issue by JGJP** [dazuaz/responsive-loader#63]
I'm aware of the discussion in #3 but it seems that responsive-loader is able to optimize jpegs via the `quality` setting. Why is it possible to optimize jpegs but not png? Or can optipng and/or pngquant be added? I'd love to be able to handle both jpegs and pngs with this loader.

**Comment by herrstucki** [comment]
I don't know how much optimization is actually needed with jimp/sharp but it would be a good idea to support all the output-specific options of either adapter, see http://sharp.dimens.io/en/stable/api-output/

**Comment by kasvtv** [comment]
Has anyone found a good workflow for minifying the png's that this plugin creates? It is currently quite a big problem for me, downsizing a 5kB PNG results in a 15kB PNG...

**Comment by AlexOuttaspace** [comment]
> Has anyone found a good workflow for minifying the png's that this plugin creates? It is currently quite a big problem for me, downsizing a 5kB PNG results in a 15kB PNG...

I'm currenly solving this with using imagemin-webpack-plugin. However with it build takes longer.

**Comment by joaocarmo** [comment]
@tettoffensive , try what @AlexOuttaspace suggested using [imagemin-webpack](https://github.com/itgalaxy/imagemin-webpack) which will optimize all the images that have been handled by the build.

**Comment by tettoffensive** [comment]
@joaocarmo I ended up following the suggestion here: https://github.com/herrstucki/responsive-loader/issues/3#issuecomment-484368908 although it took me a day and a half to get working. Had to fork my own version of the srcset-loader repo and update a few dependencies to get it to build on osx.

**Comment by joaocarmo** [comment]
@tettoffensive , did you try [pwa-srcset-loader](https://www.npmjs.com/package/pwa-srcset-loader)? It seems to have a (as of now, at least) somehow recent release.

**Comment by tettoffensive** [comment]
No, but at this point I have it working. Gonna stick with it for now

**Comment by strarsis** [comment]
Luckily PNGs are usually lossless. It is possible to use the webpack imagemin plugin and its `test` field to have a glob that only matches these PNGs and optimize them using the imagemin png plugins.

**Comment by dazuaz** [comment]
Sharp supports PNG optimization only if libvips is compiled with support for libimagequant 

It does not come as default in the bundled libvips binaries that are in the npm package because:

> The prebuilt binaries provided by sharp for libvips and its dependencies do not include GPL-licensed or patent-encumbered software.

_Originally posted by @lovell in https://github.com/lovell/sharp/issues/1793#issuecomment-512346455_

I don't think
To optimize all png images that webpack emits you could use:
```
npm install imagemin-webpack imagemin imagemin-pngquant
```
```javascript
// webpack config
...
  plugins: [
    new ImageminPlugin({
      test: /.(png)$/i,
      bail: false, // Ignore errors on corrupted images
      cache: true,
      imageminOptions: {
        // Before using imagemin plugins make sure you have added them in `package.json` (`devDependencies`) and installed them

        // Lossless optimization with custom option
        // Feel free to experiment with options for better result for you
        plugins: [["pngquant"]],
      },
      loader: false,
    }),
  ],
...
```

**Comment by AaronPorts** [comment]
Maybe it makes sense to drop optimization settings and leave it to [image-minimizer-webpack-plugin](https://github.com/webpack-contrib/image-minimizer-webpack-plugin)?

**Comment by dazuaz** [comment]
Sharp makes it easy to compress ```jpg/webp/avif```, do not think another loader is necessary in the majority of scenarios
