### ISSUE TITLE
Dynamic name templating

### ISSUE THREAD

**Issue by JulienAramino** [dazuaz/responsive-loader#77]
Hello,

It could very usefull to have different name for an image  based on an attribute.
For example:
A name in french set with i18n and another one in english.
2 pictures will be generated.
This is mainly for SEO optimisation.
It could be also usefull to set the name dynamically even for a unique language.

Do you think it could be, is it already possible ?

Thanks

**Comment by dazuaz** [comment]
This should be already posible by setting the ```name``` in the query parameter

```
const en = require('../cat-1000.jpg?name=the-cat-[hash:7]-[width].[ext]')
const fr = require('../cat-1000.jpg?name=le-chat-[hash:7]-[width].[ext]')
```

But, SPAs internationalization libraries would play nice conditionally loading different images elements --
