### ISSUE TITLE
Possibility to not emit the file?

### ISSUE THREAD

**Issue by bitttttten** [dazuaz/responsive-loader#87]
When doing SSR with this loader, it would be nice to have an option to not emit the file. The docs and source code gave no hints of it being possible.

I imagine the option would look like the file-loader:

```js
            {
              test: [/\.jpe?g$/, /\.png$/, /\.webp$/],
              loader: 'responsive-loader',
              options: {
                adapter: require('responsive-loader/sharp'),
                name: 'static/media/[name].[hash:8].[ext]',
                emitFile: false,
              },
            },
````

**Comment by endiliey** [comment]
I believe this is useful too

maybe https://github.com/herrstucki/responsive-loader/pull/67 can solve this

@herrstucki any thoughts on the possibility of this ?

**Comment by bitttttten** [comment]
I forked the repo and made this change and it is working great :)

**Comment by dazuaz** [comment]
This feature has been added
