### ISSUE TITLE
IntersectionObserver breaks responsive images generation

### ISSUE THREAD

**Issue by gacallea** [dazuaz/responsive-loader#98]
Hi, implementing lazy loading (either with vanilla js or with lozad js) breaks responsive loader images generation.

lozad issue is described here: https://github.com/ApoorvSaxena/lozad.js/issues/216

vanilla js version with IntersectionObsever breaks all images. Meaning that responsive loader won't generate any.

please let me know if you need more details

**Comment by dazuaz** [comment]
@gacallea please reopen if the issue persists, closing old issues.
